In [4]:
import pandas as pd

df = pd.read_csv('../data/raw/rows.csv/rows.csv')
df.head()

C:\Users\rautr\AppData\Local\Temp\ipykernel_11928\3375138476.py:3: DtypeWarning: Columns (4,5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/rows.csv/rows.csv')

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,05/10/2019,In progress,Yes,NaN,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,NaN,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,05/10/2019,Closed with explanation,Yes,NaN,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,NaN,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,NaN,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,NaN,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,05/10/2019,In progress,Yes,NaN,3238460

In [ ]:
df = df[['Product', 'Issue', 'Consumer complaint narrative']]
df.head()

,Product,Issue,Consumer complaint narrative
0,Checking or savings account,Managing an account,NaN
1,Checking or savings account,Managing an account,NaN
2,Debt collection,Communication tactics,NaN
3,"Credit reporting, credit repair services, or o...",Incorrect information on your report,NaN
4,Checking or savings account,Managing an account,NaN

In [ ]:
df = df.dropna(subset=['Consumer complaint narrative'])
df.shape

(4360, 3)

In [ ]:
df = df.rename(columns={
    'Consumer complaint narrative': 'text',
    'Product': 'category',
    'Issue': 'subcategory'
})

df.head()

,category,subcategory,text
29904,"Credit reporting, credit repair services, or o...",Incorrect information on your report,The Summer of XX/XX/2018 I was denied a mortga...
30629,"Credit reporting, credit repair services, or o...",Incorrect information on your report,There are many mistakes appear in my report wi...
30735,"Credit reporting, credit repair services, or o...",Incorrect information on your report,There are many mistakes appear in my report wi...
30795,"Credit reporting, credit repair services, or o...",Incorrect information on your report,There are many mistakes appear in my report wi...
30807,"Credit reporting, credit repair services, or o...",Incorrect information on your report,There are many mistakes appear in my report wi...

In [ ]:
import re

def clean_text(t):
    t = str(t).lower()                              # lowercase
    t = re.sub(r'<.*?>', ' ', t)                    # remove HTML tags
    t = re.sub(r'http\S+|www\S+', ' ', t)           # remove URLs
    t = re.sub(r'[^a-zA-Z ]', ' ', t)               # remove numbers + punctuation
    t = re.sub(r'\s+', ' ', t).strip()              # remove extra spaces
    return t

df['clean_text'] = df['text'].apply(clean_text)
df[['text', 'clean_text']].head()

,text,clean_text
29904,The Summer of XX/XX/2018 I was denied a mortga...,the summer of xx xx i was denied a mortgage lo...
30629,There are many mistakes appear in my report wi...,there are many mistakes appear in my report wi...
30735,There are many mistakes appear in my report wi...,there are many mistakes appear in my report wi...
30795,There are many mistakes appear in my report wi...,there are many mistakes appear in my report wi...
30807,There are many mistakes appear in my report wi...,there are many mistakes appear in my report wi...

In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def remove_stopwords(t):
    return " ".join([word for word in t.split() if word not in stop_words])

df['clean_text'] = df['clean_text'].apply(remove_stopwords)

df[['text', 'clean_text']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,text,clean_text
29904,The Summer of XX/XX/2018 I was denied a mortga...,summer xx xx denied mortgage loan due charge x...
30629,There are many mistakes appear in my report wi...,many mistakes appear report without understanding
30735,There are many mistakes appear in my report wi...,many mistakes appear report without understanding
30795,There are many mistakes appear in my report wi...,many mistakes appear report without understanding
30807,There are many mistakes appear in my report wi...,many mistakes appear report without understanding

In [ ]:
df.to_csv("cleaned_complaints.csv", index=False)